import Head from "next/head";
import { Inter } from "next/font/google";
import { Dashboard } from "@/modules/Dashboard/Dashboard";
import { secrets } from "../../creds";
import { setCookie } from "cookies-next";

const inter = Inter({ subsets: ["latin"] });

type SpotifyAccessToken = {
  expires_in: string;
  access_token: string;
};

export const getAccessToken = async (): Promise<SpotifyAccessToken> => {
  const result = await fetch("https://accounts.spotify.com/api/token", {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: `grant_type=client_credentials&client_id=${secrets.spotify.client_id}&client_secret=${secrets.spotify.client_secret}`,
  });
  const response = await result.json();
  return await response;
};

export const getServerSideProps = async ({ req, res }) => {
  const spotifyAccessToken = await getAccessToken();
  setCookie("spotify_token", spotifyAccessToken.access_token, {
    req,
    res,
    maxAge: parseInt(spotifyAccessToken.expires_in),
    path: "/",
  });

  return {
    props: {},
  };
};

const Home = () => {
  return (
    <>
      <Head>
        <title>booker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
    </>
  );
};

export default Home;
