import Head from "next/head";
import { Dashboard } from "@/modules/Dashboard/Dashboard";
import { secrets } from "../../creds";
import { setCookie } from "cookies-next";
import axios from "axios";

type SpotifyAccessToken = {
  expires_in: string;
  access_token: string;
};

export const getAccessToken = async (): Promise<SpotifyAccessToken> => {
  const headers = { "Content-Type": "application/x-www-form-urlencoded" };
  const body = `grant_type=client_credentials&client_id=${secrets.spotify.client_id}&client_secret=${secrets.spotify.client_secret}`;

  return axios
    .post("https://accounts.spotify.com/api/token", body, {
      headers: headers,
    })
    .then(function (response) {
      return response.data;
    })
    .catch(function (error) {
      console.log(error);
    });
};

export const getServerSideProps = async ({ req, res }) => {
  const spotifyAccessToken = await getAccessToken();
  setCookie("spotify_token", spotifyAccessToken.access_token, {
    req,
    res,
    maxAge: parseInt(spotifyAccessToken.expires_in),
    path: "/",
  });

  return {
    props: {},
  };
};

const Home = () => {
  return (
    <>
      <Head>
        <title>booker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
    </>
  );
};

export default Home;
